### ISSUE TITLE
failing test

### ISSUE THREAD

**Issue by mjvankampen** [pepe82sh/ConanCmakeToolchainGenerator#2]
When I run 
conan create . demo/testing -s compiler=gcc -s compiler.libcxx=libstdc++ -s
 compiler.version=5.4

I get:
cmake_toolchain_generator/0.1@demo/testing (test package): ERROR: Generator CmakeToolchain(file:conan_toolchain.cmake) failed
'HelloTestConan' object has no attribute 'install_folder'
ERROR: 'HelloTestConan' object has no attribute 'install_folder'

I'm not sure where this comes from?

[edit]
It seems that CMakeDefinitionsBuilder get_definitions is using the install folder.

**Comment by peter-moran** [comment]
I've also seen this, and don't have a good solution other than getting Conan main line to make a code change.

Specially, it is needed in this part of `CMakeDefinitionsBuilder.get_definitions` only when using the `cmake_find_package` generator.
```
        # Adjust automatically the module path in case the conanfile is using the
        # cmake_find_package or cmake_find_package_multi
        install_folder = self._conanfile.install_folder.replace("\\", "/")
        if "cmake_find_package" in self._conanfile.generators:
            definitions["CMAKE_MODULE_PATH"] = install_folder

        if "cmake_find_package_multi" in self._conanfile.generators:
            # The cmake_find_package_multi only works with targets and generates XXXConfig.cmake
            # that require the prefix path and the module path
            definitions["CMAKE_PREFIX_PATH"] = install_folder
            definitions["CMAKE_MODULE_PATH"] = install_folder
```

One fix that Conan could implement is to only calculate `install_folder` if needed. Right now it is always calculated, and recently it was made so generators do not have `install_folder`.

My hacky fix so far has been to assign an empty string to `install_folder`.

**Comment by peter-moran** [comment]
https://github.com/conan-io/conan/issues/5568 should also fix this

**Comment by pepe82sh** [comment]
Sorry for the late reply. I did not setup auto assignment of issues and got no notification at all regarding this issue. conan-io/conan#5568 is released and fixed it. I also setup some CI for this project, hoping that I'll catch these issues earlier next time.
